In [2]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv('dataset/Training.csv')
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
df.shape

(4920, 133)

In [5]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [6]:
len(df['prognosis'].unique())

41

### train test split

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [8]:
X=df.drop('prognosis', axis=1)
y=df['prognosis']
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=20)

In [9]:
le=LabelEncoder()
le.fit(y)
Y=le.transform(y)

In [10]:
X_train.shape,X_train.shape

((3444, 132), (3444, 132))

### Train top model

In [11]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix

In [12]:
#create a dictionary to store models
models={
    'SVC': SVC(kernel='linear'),
    'RandomForest':RandomForestClassifier(n_estimators=100, random_state=4),
    'GBC': GradientBoostingClassifier(n_estimators=100, random_state=4),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'MNB': MultinomialNB()
}
for model_name, model in models.items():
    model.fit(X_train, y_train)
    
    pred=model.predict(X_test)
    
    a= accuracy_score(y_test, pred)
    c= confusion_matrix(y_test, pred)
    print(f"{model_name}, accuracy: {a}\n")
    print(f"{model_name}, confusion matrix: \n{c}\n")

SVC, accuracy: 1.0

SVC, confusion matrix: 
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]

RandomForest, accuracy: 1.0

RandomForest, confusion matrix: 
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]

GBC, accuracy: 1.0

GBC, confusion matrix: 
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]

KNN, accuracy: 1.0

KNN, confusion matrix: 
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]

MNB, accuracy: 1.0

MNB, confusion matrix: 
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0

In [13]:
import pickle
svc = SVC()
svc.fit(X_train, y_train)

# Save the model
with open('model/svc.pkl', 'wb') as file:
    pickle.dump(svc, file)

In [14]:
import pickle

# Load the model
with open('model/svc.pkl', 'rb') as file:
    svc = pickle.load(file)



In [15]:
# Ensure X_test is defined and correctly shaped
prediction = svc.predict(X_test.iloc[508].values.reshape(1, -1))
print(prediction)

['Osteoarthristis']


c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [16]:
y_test.iloc[508]

'Osteoarthristis'

## Loading databse

In [17]:
des=pd.read_csv('dataset/symtoms_df.csv')
precaution= pd.read_csv('dataset/precautions_df.csv')
precaution.head()

Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation   
1           1         Malaria          Consult nearest hospital   
2           2         Allergy                    apply calamine   
3           3  Hypothyroidism                     reduce stress   
4           4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [18]:
workout=pd.read_csv('dataset/workout_df.csv')
workout.head(1000)

Unnamed: 0.1  Unnamed: 0           disease  \
0               0           0  Fungal infection   
1               1           1  Fungal infection   
2               2           2  Fungal infection   
3               3           3  Fungal infection   
4               4           4  Fungal infection   
..            ...         ...               ...   
405           405         405          Impetigo   
406           406         406          Impetigo   
407           407         407          Impetigo   
408           408         408          Impetigo   
409           409         409          Impetigo   

                               workout  
0                   Avoid sugary foods  
1                   Consume probiotics  
2            Increase intake of garlic  
3               Include yogurt in diet  
4                Limit processed foods  
..                                 ...  
405  Consult a healthcare professional  
406     Follow medical recommendations  
407                   Avoid scratching  
408        Take prescribed antibiotics  
409                Practice wound care  

[410 rows x 4 columns]

In [19]:
description=pd.read_csv('dataset/description.csv')
description.head()

Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

In [20]:
medi=pd.read_csv('dataset/medications.csv')
medi.head()

Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [36]:
diet=pd.read_csv('dataset/diets.csv')
diet.head()

Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

In [22]:
def helper(dis):
    descr=description[description['Disease']==dis]['Description']
    descr=" ".join([w for w in descr])
    
    pre=precaution[precaution['Disease']==dis][['Precaution_1', "Precaution_2",'Precaution_3','Precaution_4']]
    pre=[w for w in pre.values]
    
    med=medi[medi['Disease']==dis]['Medication']
    med=[w for w in med.values]
    
    die = diet[diet['Disease'] == dis]['Diet']
    die = [w for w in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']
    
    return descr,pre,med,die,wrkout

In [30]:

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}

def get_predicted_values(patient_symptoms):
    vector = np.zeros(len(symptoms_dict))
    
    for item in patient_symptoms:
        vector[symptoms_dict[item]] = 1
    return svc.predict([vector])[0]
    

symptoms = input('Enter separating by comma(,) : ')
user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [s.strip("[]' ") for s in user_symptoms]
predicted_disease = get_predicted_values(user_symptoms)
predicted_disease
        


c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


'Allergy'

In [31]:
descr,pre,med,die,wrkout=helper(predicted_disease)

In [32]:
print(f"===================={predicted_disease}===================\n")
print(descr)
print("\n======================Precautions=====================")
i=1
for p in pre[0]:
    print(f"{i}: {p}")
    i+=1
    
print("\n====================== Medication =====================")
i=1
for p in med:
    print(f"{i}: {p}")
    i+=1
    
print("\n====================== Workout =====================")
i=1
for p in wrkout:
    print(f"{i}: {p}")
    i+=1
    
print("\n====================== Diet =====================")
i=1
for p in die:
    print(f"{i}: {p}")
    i+=1

====================Allergy===================

Allergy is an immune system reaction to a substance in the environment.

======================Precautions=====================
1: apply calamine
2: cover area with bandage
3: nan
4: use ice to compress itching

====================== Medication =====================
1: ['Antihistamines', 'Decongestants', 'Epinephrine', 'Corticosteroids', 'Immunotherapy']

====================== Workout =====================
1: Avoid allergenic foods
2: Consume anti-inflammatory foods
3: Include omega-3 fatty acids
4: Stay hydrated
5: Eat foods rich in vitamin C
6: Include quercetin-rich foods
7: Consume local honey
8: Limit processed foods
9: Include ginger in diet
10: Avoid artificial additives

====================== Diet =====================
1: ['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']


In [33]:
import sklearn
print(sklearn.__version__)

1.4.1.post1
